### ISSUE TITLE
502: Bad Gateway after wiz-config

### ISSUE THREAD

**Issue by AndyZaa** [heleon19/node-red-contrib-wiz-local-control#2]
Hi, thanks for this NR contribution. I just picked up my first WiZ bulb and excited to use it in NR. However, when I create a new wiz-config and enter my bulb IP, I get the dreaded "502: Bad Gateway". Then the only way to recover is to restore a full backup. It seems to happen as soon as I fill in the wiz-config because then I add a couple of inject nodes to test on/off and the inject nodes won't even respond. I suspect I'm doing something wrong in the wiz-config. Can you or anyone share documentation of how to configure wiz-config or a working flow so that I can compare with what I'm trying?

**Comment by AndyZaa** [comment]
I've been back at this several times. The WiZ bulb works fine in the Philips WiZ app (using V1 and not the terrible V2). I have "Allow Local Control" set to On in the WiZ app. The Home Assistant native WiZ integration works fine. In Node-RED I install the node-red-contrib-wiz-local-control node and drag the WiZ Device into the editor. I add two inject nodes for boolean True and False, and wire them to the input of the WiZ Device. Then I double click the Wiz Device and open the "Add new wiz-config config node". In properties I Name it WiZConfig and set the Interface to enp3s0 (from HA Settings > System > Network > Network Adapter) and select Add. At that point Node-RED goes unresponsive and the mouse pointer can't select the inject triggers or anything else. I've tried variations on the Interface, from eth0 to the actual IP address. Always the same - and when I restart HA to recover, I get the unrecoverable "502: Bad Gateway". Then I have to do a full restore from before adding the node.

Just to be sure it's not a Node-RED issue form some other node, I've created several other flows before adding the node-red-contrib-wiz-local-control node and they all work fine. Could it be some negative interaction with another node? I do a lot of Node-RED and have created quite a few flows. Node-RED has been pretty robust for me though. I would really like to use more WiZ devices in my system so would love to get this node working. Please let me know how I can help.

**Comment by heleon19** [comment]
Hello
With the wiz-conifg I have configured eth0 as interface.
With the wiz-device as IP the IP of the lamp, example 192.168.1.35.

In the background the wiz-local-control from https://gitlab.com/wizlighting/wiz-local-control is used. My node is only a wrapper around this library, if necessary you can ask there.

Otherwise please post the log of the Node-RED here.

Regards Reto

**Comment by kccrkccr** [comment]
Hi, for "Interface" I just used the name of my wireless network. When I had two config nodes, even if I wasn't using one of them, everything crashed (and became non-responsive as you describe). I had to run node-red in safe mode ("node-red --safe" in windows cmd window) in order to disable the second config in my drop-down menu. That worked, so then I deleted it entirely. Hope this helps

**Comment by AndyZaa** [comment]
Good tip on node-red in safe mode - I didn't know about that. I'll have to find the command for Debian.

**Comment by heleon19** [comment]
Hi, my configuration looks like this!
![image](https://user-images.githubusercontent.com/10326318/229891702-f76e125e-6abc-4267-b64b-b35524b405ae.png)
![image](https://user-images.githubusercontent.com/10326318/229891837-94df995d-464c-45b1-8249-87b7cae2af07.png)
