### ISSUE TITLE
New Feature Request - Powermeter

### ISSUE THREAD

**Issue by real-intruder** [heleon19/node-red-contrib-wiz-local-control#3]
The Plugin Works Perfect with on/off Commands for my Smart Plug with Powermeter.
Is it planned to call up the consumption or current performance?

Thanks

**Comment by AndyZaa** [comment]
Hi @real-intruder, since your instance is working fine, could you share your wiz-config parameters or even an example flow with me? I'm crashing Node-RED with this node and perhaps I'm doing something really dumb in the config. Thanks.

**Comment by kccrkccr** [comment]
I'm with Andy, I can't get a damn thing to work, can you please share your settings?

**Comment by kccrkccr** [comment]
@AndyZaa I got it working. For "Interface" I put the name of my wireless network. The "name" of the config node didn't seem to matter, I used WiZ.

When I had two config nodes (even if I wasn't using them), node-red crashed. I had to pick the second one from the drop-down menu in the node and then either "disable" it or delete it. Because node-red was crashing so much, to do that it was necessary to run node-red in safe mode, ie on Windows I typed node-red --safe in the command window. I hope this helps.

**Comment by AndyZaa** [comment]
Thanks @kccrkccr. When you say you put the name of your wireless network, do you mean like MyWireless_2.4G, not the numerical IP of my router? I don't think I tried the former. The duplicate config nodes issue is interesting. I don't know if I had that because each time I crashed node-red I reloaded the backup. I'm in the midst of adding some other gear so I'll let that get to steady state and then try the WiZ node again.

**Comment by kccrkccr** [comment]
Yes, exactly, the "human-friendly" name like My_Wireless_2.4G. Nothing I needed to go into my router settings to get. Good luck!

**Comment by heleon19** [comment]
Hi, I have tested the power function, unfortunately all values are 0. currently no extensions are planned
